src/src/Entity/Comment.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\CommentRepository")
 */
class Comment
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer")
     */
    private $article_id;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $creator_id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $first_name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $last_name;

    /**
     * @ORM\Column(type="datetime")
     */
    private $creation_date;

    /**
     * @ORM\Column(type="text")
     */
    private $content;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getArticleId(): ?int
    {
        return $this->article_id;
    }

    public function setArticleId(int $article_id): self
    {
        $this->article_id = $article_id;

        return $this;
    }

    public function getCreatorId(): ?int
    {
        return $this->creator_id;
    }

    public function setCreatorId(?int $creator_id): self
    {
        $this->creator_id = $creator_id;

        return $this;
    }

    public function getFirstName(): ?string
    {
        return $this->first_name;
    }

    public function setFirstName(string $first_name): self
    {
        $this->first_name = $first_name;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->last_name;
    }

    public function setLastName(string $last_name): self
    {
        $this->last_name = $last_name;

        return $this;
    }

    public function getCreationDate(): ?\DateTimeInterface
    {
        return $this->creation_date;
    }

    public function setCreationDate(\DateTimeInterface $creation_date): self
    {
        $this->creation_date = $creation_date;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }
}

src/src/Entity/User.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 */
class User implements UserInterface
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     * @Assert\NotBlank
     * @Assert\Email
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     * @Assert\NotBlank
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank
     */
    private $first_name;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank
     */
    private $last_name;

    /**
     * @ORM\Column(type="boolean")
     */
    private $is_blocked;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $last_login;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string)$this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string)$this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getSalt()
    {
        // not needed when using the "bcrypt" algorithm in security.yaml
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getFirstName(): ?string
    {
        return $this->first_name;
    }

    public function setFirstName(string $first_name): self
    {
        $this->first_name = $first_name;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->last_name;
    }

    public function setLastName(string $last_name): self
    {
        $this->last_name = $last_name;

        return $this;
    }

    public function getIsBlocked(): ?bool
    {
        return $this->is_blocked;
    }

    public function setIsBlocked(bool $is_blocked): self
    {
        $this->is_blocked = $is_blocked;

        return $this;
    }

    public function getLastLogin(): ?\DateTimeInterface
    {
        return $this->last_login;
    }

    public function setLastLogin(?\DateTimeInterface $last_login): self
    {
        $this->last_login = $last_login;

        return $this;
    }
}

src/src/Controller/EtiController.php
<?php

namespace App\Controller;

use App\Entity\BlogPost;
use App\Repository\BlogPostRepository;
use Exception;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Contracts\Translation\TranslatorInterface;

/**
 * Class EtiController
 */
class EtiController extends AbstractController
{
    /**
     * @Route("/", name="homepage")
     * @return Response
     */
    public function blogHomepage()
    {
        $user = $this->getUser();
        return $this->render('eti/blog/homepage.html.twig', $user == null ? [] : ["user" => $user]);
    }

    /**
     * @Route("/first/page", name="first_page")
     * @param TranslatorInterface $translator
     * @return Response
     * @throws Exception
     */
    public function randomNumber(TranslatorInterface $translator)
    {
        $number = random_int(0, 100);

        return $this->render('eti/blog/first_page.html.twig', [
            'number' => $number,
            'translated_php' => $translator->trans('Translated string'),
            'translated_php_pl' => $translator->trans('Translated string', [], 'messages', 'pl_PL')
        ]);
    }
}

src/templates/eti/blog/first_page.html.twig
{# templates/blog/first_page.html.twig #}
{% extends 'eti/blog/layout.html.twig' %}

{% block title %}Blog Index / FirstPage{% endblock %}

{% block content %}
    <p> Lucky number: {{ number }} </p>
    <div>
        <p>Default PHP translation: {{ translated_php }} <br />
        Template translation: {% trans %}Translated string{% endtrans %}</p>
    </div>
    <div>
        <p>Forced PL translation: {{ translated_php_pl }}<br />
        PL Forced Template translation: {{ 'Translated string'|trans({}, 'messages', 'pl_PL') }}</p>
    </div>
{% endblock %}

src/templates/eti/blog/homepage.html.twig
{# templates/eti/blog/homepage.html.twig #}

{% extends 'eti/blog/layout.html.twig' %}

{% block title %}Homepage{% endblock %}

{% block content %}
    <p> Welcome on ETI Blog Homepage! </p>
{% endblock %}

src/templates/eti/blog/layout.html.twig
{# templates/blog/layout.html.twig #}
{% extends 'base.html.twig' %}

{% block body %}
    <h1>ETI Blog</h1>

    {% block content %}{% endblock %}
{% endblock %}

src/templates/eti/blog/post_view.html.twig
{# templates/blog/first_page.html.twig #}
{% extends 'eti/blog/layout.html.twig' %}

{% block title %}
	{{ article.title }}
{% endblock %}

{% block content %}
	<h2>
		{{ article.title }}
	</h2>
	<h3>
		{{ article.summary }}
	</h3>
	<p>
		Author:
		{{ author.firstName }}
		{{ author.lastName }}
	</p>
	{% if user is not null and user.id == author.id %}
		<a href="{{ path('post_edit', {id: article.id}) }}">Edit</a>
	{% endif %}
	<p>
		Creation date:
		{{ article.creationDate|date('Y-m-d H:i:s') }}
	</p>
	<p>
		{{ article.content }}</p>

	<hr/>
	<ul>
		{% for comment in comments %}
			<li>{{ comment.firstName }}
				{{ comment.lastName }},
				{{ comment.creationDate|date('Y-m-d H:i:s') }}
				-->
				{{ comment.content }}</li>
		{% endfor %}
	</ul>

	{% if isCommentFormString %}
		<h2>{{ commentForm }}</h2>
	{% else %}
		{{ form(commentForm) }}{% endif %}
	{% endblock %}

src/templates/eti/blog/posts.html.twig
{# templates/blog/first_page.html.twig #}
{% extends 'eti/blog/layout.html.twig' %}

{% block title %}Blog Index / Articles to read{% endblock %}

{% block content %}
    <p> Posts: </p>

    <ul>
    {% for article in articles %}
        <li>
            <a href="{{ path('post_details', {id: article.id}) }}">
                {{ article.title }} - {{ article.summary }}
            </a>
        </li>
    {% endfor %}
    </ul>
{% endblock %}

src/templates/eti/blog/register.html.twig
{# templates/blog/first_page.html.twig #}
{% extends 'eti/blog/layout.html.twig' %}

{% block title %}Blog Index / Login {% endblock %}

{% block content %}
<h2>{{ error | default("") }}</h2>
    
{# Simple form renering #}
    {{ form(register_form) }}
{% endblock %}